### ISSUE TITLE
Black screen: the connection to the server seems to fail

### ISSUE THREAD

**Issue by jsimb** [nilp0inter/pyagar#1]
The connection to the server seems to fail, as there is nothing else printed to the console and the game window remains black.

```
$ pyagar play
INFO:pyagar:Starting pyagar!
INFO:pyagar:Version 0.0.7
INFO:pyagar:Connecting to server 151.80.96.53:1504
█ 
```

FYI, I started by installing an (older) version of pyagar found here https://pypi.python.org/pypi/pyagar and I had the same problem. I then downloaded the most recent code found on this repository, and installed it using:

```
$ python3 setup.py install
```

It didn't fix the problem. I assume the newer install overwrote the older _pyagar_ command.

**Comment by nilp0inter** [comment]
Please, enable the debug mode executing `pyagar -d play` and paste the output back.

**Comment by jsimb** [comment]
I uninstalled `python3-pip` and it now seems to work fine.

```
username@username:~$ pyagar -d play
INFO:pyagar:Starting pyagar!
INFO:pyagar:Version 0.0.7
DEBUG:pyagar:Server: 151.80.98.51:1504
DEBUG:pyagar:Token: J7HGMDUEA3M8Y2MG
INFO:pyagar:Connecting to server 151.80.98.51:1504
DEBUG:pyagar:Connected!
DEBUG:pyagar:Mouse button pressed.
DEBUG:pyagar:Spawn sent.
DEBUG:pyagar:Move sent (x=4890, y=-907)
DEBUG:pyagar:Move sent (x=4895, y=-907)
DEBUG:pyagar:Move sent (x=4900, y=-901)
DEBUG:pyagar:Move sent (x=4912, y=-886)
```

However, the game window remains black.

**Comment by Gjum** [comment]
This issue may be related to [this code](https://github.com/nilp0inter/pyagar/blob/develop/pyagar/messages.py#L136-L137), where you read int16 instead of int32.

**Comment by nilp0inter** [comment]
@jsimb I think your problem is related to your SDL installation, because the log you posted looks good.

I've experienced myself the same issue in the past, the problem was the window I created was bigger than my screen resolution.

Can you please try the parameter `pyagar --disable-hw` and/or try to change to fullscreen mode pressing the key "f" in the black window.

Also try to run the spectator mode with `pyagar spectate`.

BTW, are you running on linux or windows?

**Comment by nilp0inter** [comment]
@Gjum, Thank you for pointing this out. I've made the change to match the current implementation and I discover a very interesting thing: the second number in the handshake is a protocol version so the server can send to the client data that it can understand.  Pretty neat! fcc926b4631c28232c69d40c44c1538800afee2a

I suppose this is because the new client for smartphones. Don't you think?

**Comment by jsimb** [comment]
I'm running Ubuntu 15.04 (vivid)

The command `pyagar --disable-hw play` made it work, but the game doesn't respond well to the mouse movements (trackpad).
`pyagar spectate` only displayed a black window, same for fullscreen mode.

I was able to install Gjum's version of agar, though.

How do you suggest I fix my SDL installation ?

**Comment by nilp0inter** [comment]
@jsimb For some reason the hardware acceleration is not working in your setup. This is why the `--disable-hw` makes it work.

I'll try it in Ubuntu 15.04 as soon as possible and tell you what I found.

Two more questions to help me out what is happening:
- Are you running Ubuntu in a virtual machine or in bare metal?
- Can you please paste the output of `glxinfo`?

**Comment by jsimb** [comment]
I am running Ubuntu in bare metal, not in a virtual machine. You can find the specifications of my laptop computer <a href=http://goo.gl/0JRh3i>here</a>.

Here is the output of `glxinfo` : http://pastebin.com/LMYMR8j4

**Edit:**

I gave it another try, this time on a desktop computer also running bare metal Ubuntu 15.04.
The version of python is`3.4.1`

I installed the following libraries: `libsdl2-dev`, `libsdl2-ttf-dev`and `libsdl2-gfx-dev`
Installing **pyagar** with `pip` or `pip3` didn't work. You can find a console dump <a href=http://pastebin.com/CGMZmEmw>here</a>.

I then downloaded the code from this repository and installed it using `$ sudo python3 setup.py install`

`$ pyagar --disable-hw play` allows me to run the game at ~5fps, while `$ pyagar play` only gives me a black game window.

Is there anything i'm not doing right ?

**Comment by nilp0inter** [comment]
You are doing it right. I was able to reproduce the error with an Ubuntu installation.
I've just found the error and I am making a patch.

Thank you very much for the feedback.

**Comment by nilp0inter** [comment]
This patch should fix the issue.

@jsimb Please, test the repo version and tell me if it works for you.

**Comment by jsimb** [comment]
It works.

A first try gave me this encoding error:

```
$ python3 setup.py install
  File "setup.py", line 20
SyntaxError: Non-ASCII character '\xc3' in file setup.py on line 20, but no 
encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

This error can be solved by adding `# coding=utf-8` at the top of the file, or by removing the
`ì` character from line 20.

`$ pyagar play` works, but the game is very "jerky" and is not really responsive to the mouse control. After a few tries I found out that the mouse cursor has to be very close to the edge of the window (far from the center) for the cell to respond well to mouse movements.

Both `$ pyagar spectate` and `pyagar bot --type=EatWhenNoPredators` work well.

Thank you very much for your time.

**Comment by nilp0inter** [comment]
I will try to improve it!

The rendering method I am using is pretty far from being good. So I will work on it

Thank you again.
